# yaml-language-server: $schema=../schema.json
tokens:
  # M0 MantraUSD on Ethereum (HubPortal)
  - addressOrDenom: "0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE"
    chainName: ethereum
    collateralAddressOrDenom: "0xd2b95283011E47257917770D28Bb3EE44c849f6F"
    connections:
      - token: ethereum|mantra|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
    decimals: 6
    logoURI: /deployments/warp_routes/mantraUSD/logo.png
    name: MANTRA USD
    standard: EvmM0PortalLite
    symbol: mantraUSD
  # M0 USDSC on Soneium (SpokePortal)
  - addressOrDenom: "0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE"
    chainName: mantra
    collateralAddressOrDenom: "0xd2b95283011E47257917770D28Bb3EE44c849f6F"
    connections:
      - token: ethereum|ethereum|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
    decimals: 6
    logoURI: /deployments/warp_routes/mantraUSD/logo.png
    name: MANTRA USD
    standard: EvmM0PortalLite
    symbol: mantraUSD
