tokens:
  - chainName: fluent
    standard: EvmHypCollateral
    decimals: 18
    symbol: BLEND
    name: BLEND
    addressOrDenom: "0x2bef59e84615371304bd731601f6344F5F304504"
    collateralAddressOrDenom: "0x1385B8f55A84f2BdA13EeD4099d29Eae03d553b2"
    connections:
      - token: sealevel|solanamainnet|4iQfUG5RC58qAdwiLUUv3xmUnADviy4TQ1pqJVrSR2fE
  - chainName: solanamainnet
    standard: SealevelHypSynthetic
    decimals: 9
    symbol: BLEND
    name: BLEND
    addressOrDenom: 4iQfUG5RC58qAdwiLUUv3xmUnADviy4TQ1pqJVrSR2fE
    collateralAddressOrDenom: BWsnyEa1XtsNRdgPaDoA1WVUonF7BBGZTd2zc72NQsWT
    connections:
      - token: ethereum|fluent|0x2bef59e84615371304bd731601f6344F5F304504
