# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x7f37ca42A1a39f736339CE12FC2eB8e9EA88FFe5"
    chainName: arbitrumsepolia
    collateralAddressOrDenom: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
    connections:
      - token: ethereum|sepolia|0xe0F3680b09751b965CFA24f02f5aa58f0E12343a
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xe0F3680b09751b965CFA24f02f5aa58f0E12343a"
    chainName: sepolia
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: ethereum|arbitrumsepolia|0x7f37ca42A1a39f736339CE12FC2eB8e9EA88FFe5
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
