tokens:
  - addressOrDenom: test_hyp_warp_token_sol.aleo/aleo19nf6jcxryza3v5rwxchx7g5ew2wy44pqkeys7v4pmy29v3scdszqnyw5pl
    chainName: aleotestnet
    connections:
      - token: sealevel|solanatestnet|84nEGHMEeP1qSyD8Bw2KZPeW4JXjeFRRMiuzwTvt83Yz
    decimals: 9
    logoURI: /deployments/warp_routes/SOL/logo.svg
    name: Solana
    standard: AleoHypSynthetic
    symbol: SOL
  - addressOrDenom: 84nEGHMEeP1qSyD8Bw2KZPeW4JXjeFRRMiuzwTvt83Yz
    chainName: solanatestnet
    connections:
      - token: aleo|aleotestnet|test_hyp_warp_token_sol.aleo/aleo19nf6jcxryza3v5rwxchx7g5ew2wy44pqkeys7v4pmy29v3scdszqnyw5pl
    decimals: 9
    logoURI: /deployments/warp_routes/SOL/logo.svg
    name: Solana
    standard: SealevelHypNative
    symbol: SOL
