tokens:
  - addressOrDenom: test_hyp_warp_token_haqrlm.aleo/aleo1xjf4zp327gjwm9cadyc3tjqvlteuvyuqpm3cv84yesdxak840vgqw9qagk
    chainName: aleotestnet
    connections:
      - token: sealevel|solanatestnet|84nEGHMEeP1qSyD8Bw2KZPeW4JXjeFRRMiuzwTvt83Yz
    decimals: 9
    logoURI: /deployments/warp_routes/SOL/logo.svg
    name: Solana
    standard: AleoHypSynthetic
    symbol: SOL
  - addressOrDenom: 84nEGHMEeP1qSyD8Bw2KZPeW4JXjeFRRMiuzwTvt83Yz
    chainName: solanatestnet
    connections:
      - token: aleo|aleotestnet|test_hyp_warp_token_haqrlm.aleo/aleo1xjf4zp327gjwm9cadyc3tjqvlteuvyuqpm3cv84yesdxak840vgqw9qagk
    decimals: 9
    logoURI: /deployments/warp_routes/SOL/logo.svg
    name: Solana
    standard: SealevelHypNative
    symbol: SOL
