# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xF2B48b6e560af8834622203a8EEff6960d6172De"
    chainName: igra
    connections:
      - token: ethereum|base|0x8DE75A8a9Ee436390429eefD343926b28768EAb7
    decimals: 8
    logoURI: /deployments/warp_routes/CBBTC/logo.svg
    name: Coinbase Wrapped BTC
    standard: EvmHypSynthetic
    symbol: cbBTC
  - addressOrDenom: "0x8DE75A8a9Ee436390429eefD343926b28768EAb7"
    chainName: base
    coinGeckoId: coinbase-wrapped-btc
    logoURI: /deployments/warp_routes/CBBTC/logo.svg
    collateralAddressOrDenom: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
    connections:
      - token: ethereum|igra|0xF2B48b6e560af8834622203a8EEff6960d6172De
    decimals: 8
    name: Coinbase Wrapped BTC
    standard: EvmHypCollateral
    symbol: cbBTC
