# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xf75ECd5eC89965EA29861D6E2d65B1215CCC82fD"
    chainName: igra
    connections:
      - token: ethereum|ethereum|0x2b751C23CbcA6366edbC5A4032F0Dc59ECeec03e
    decimals: 18
    logoURI: /deployments/warp_routes/sUSDS/logo.png
    name: Savings USDS
    standard: EvmHypSynthetic
    symbol: sUSDS
  - addressOrDenom: "0x2b751C23CbcA6366edbC5A4032F0Dc59ECeec03e"
    chainName: ethereum
    coinGeckoId: usds
    collateralAddressOrDenom: "0xa3931d71877C0E7a3148CB7Eb4463524FEc27fbD"
    connections:
      - token: ethereum|igra|0xf75ECd5eC89965EA29861D6E2d65B1215CCC82fD
    decimals: 18
    logoURI: /deployments/warp_routes/sUSDS/logo.png
    name: USDS Stablecoin
    standard: EvmHypOwnerCollateral
    symbol: sUSDS
