# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x12eDAc9B50F1014997c1bddAD23Df58b6d82De3B"
    chainName: base
    coinGeckoId: exa
    collateralAddressOrDenom: "0x1e925De1c68ef83bD98eE3E130eF14a50309C01B"
    connections:
      - token: ethereum|optimism|0x12eDAc9B50F1014997c1bddAD23Df58b6d82De3B
    decimals: 18
    logoURI: /deployments/warp_routes/EXA/logo.svg
    name: exactly
    standard: EvmHypXERC20
    symbol: EXA
  - addressOrDenom: "0x12eDAc9B50F1014997c1bddAD23Df58b6d82De3B"
    chainName: optimism
    coinGeckoId: exa
    collateralAddressOrDenom: "0x1e925De1c68ef83bD98eE3E130eF14a50309C01B"
    connections:
      - token: ethereum|base|0x12eDAc9B50F1014997c1bddAD23Df58b6d82De3B
    decimals: 18
    logoURI: /deployments/warp_routes/EXA/logo.svg
    name: exactly
    standard: EvmHypXERC20
    symbol: EXA
