# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xeAC17188D29665f57e31a0d9808a9173B9d9d632"
    chainName: igra
    coinGeckoId: igra
    connections:
      - token: ethereum|ethereum|0xb76Eaa8b8779f377248D1E9ca78550B156F5F7FB
    decimals: 18
    logoURI: /deployments/warp_routes/IKAS/logo.svg
    name: iKAS
    standard: EvmHypNative
    symbol: iKAS
  - addressOrDenom: "0xb76Eaa8b8779f377248D1E9ca78550B156F5F7FB"
    chainName: ethereum
    connections:
      - token: ethereum|igra|0xeAC17188D29665f57e31a0d9808a9173B9d9d632
    decimals: 18
    logoURI: /deployments/warp_routes/IKAS/logo.svg
    name: iKAS
    standard: EvmHypSynthetic
    symbol: iKAS
