# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x1A5E91BbCB458Ff14860025FD508aE3176F5491D"
    chainName: dotone
    connections:
      - token: ethereum|bsc|0xE41EE0A417ee43dA540eEd7b7f30a73DF8C43e6e
    decimals: 18
    name: DOTO
    standard: EvmHypNative
    symbol: DOTO
  - addressOrDenom: "0xE41EE0A417ee43dA540eEd7b7f30a73DF8C43e6e"
    chainName: bsc
    connections:
      - token: ethereum|dotone|0x1A5E91BbCB458Ff14860025FD508aE3176F5491D
    decimals: 18
    name: Wrapped DOTO
    standard: EvmHypXERC20
    symbol: WDOTO
