# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: test_hyp_warp_token_usdt.aleo/aleo17tth7t5psc44pe230y7zcxl32wzhq8452sya4v7gxc406ln5pggspn9jwe
    chainName: aleotestnet
    connections:
      - token: ethereum|sepolia|0xF6B589bA1610c1779c1d7F660aAf743b7cE6f0ae
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: AleoHypSynthetic
    symbol: USDT
  - addressOrDenom: "0xF6B589bA1610c1779c1d7F660aAf743b7cE6f0ae"
    chainName: sepolia
    coinGeckoId: tether
    collateralAddressOrDenom: "0xaa8e23fb1079ea71e0a56f48a2aa51851d8433d0"
    connections:
      - token: aleo|aleotestnet|test_hyp_warp_token_usdt.aleo/aleo17tth7t5psc44pe230y7zcxl32wzhq8452sya4v7gxc406ln5pggspn9jwe
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: USDT
    standard: EvmHypCollateral
    symbol: USDT
