# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xf09e4C8193F16019F0573F370F9A997b11f56638"
    chainName: base
    connections:
      - token: ethereum|wardenprotocol|0xc5ADACe5E2250e5497CF1eF7B4f100e10099e4c4
    decimals: 18
    logoURI: /deployments/warp_routes/WARD/logo.svg
    name: WARD
    standard: EvmHypSynthetic
    symbol: WARD
  - addressOrDenom: "0xc5ADACe5E2250e5497CF1eF7B4f100e10099e4c4"
    chainName: wardenprotocol
    connections:
      - token: ethereum|base|0xf09e4C8193F16019F0573F370F9A997b11f56638
    decimals: 18
    logoURI: /deployments/warp_routes/WARD/logo.svg
    name: WARD
    standard: EvmHypNative
    symbol: WARD
