# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189"
    chainName: arbitrum
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|arbitrum|0x824353938ee1361265097acC9E329828e3455c15
      - token: ethereum|base|0xA9A434f0aBCE2f3e7073752046545530e32DE6cF
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: ethereum|katana|0xe064aee7327b19ba636c8d8b594f73572b95ea29
      - token: sealevel|solanamainnet|5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCrossCollateralRouter
    symbol: USDC
  - addressOrDenom: "0x824353938ee1361265097acC9E329828e3455c15"
    chainName: arbitrum
    coinGeckoId: tether
    collateralAddressOrDenom: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|base|0xA9A434f0aBCE2f3e7073752046545530e32DE6cF
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: sealevel|solanamainnet|5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: USD₮0
    standard: EvmHypCrossCollateralRouter
    symbol: USD₮0
  - addressOrDenom: "0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91"
    chainName: base
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|arbitrum|0x824353938ee1361265097acC9E329828e3455c15
      - token: ethereum|base|0xA9A434f0aBCE2f3e7073752046545530e32DE6cF
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: ethereum|katana|0xe064aee7327b19ba636c8d8b594f73572b95ea29
      - token: sealevel|solanamainnet|5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCrossCollateralRouter
    symbol: USDC
  - addressOrDenom: "0xA9A434f0aBCE2f3e7073752046545530e32DE6cF"
    chainName: base
    coinGeckoId: tether
    collateralAddressOrDenom: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|arbitrum|0x824353938ee1361265097acC9E329828e3455c15
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: sealevel|solanamainnet|5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCrossCollateralRouter
    symbol: USDT
  - addressOrDenom: "0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6"
    chainName: citrea
    coinGeckoId: citrea-usd
    collateralAddressOrDenom: "0x8D82c4E3c936C7B5724A382a9c5a4E6Eb7aB6d5D"
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|arbitrum|0x824353938ee1361265097acC9E329828e3455c15
      - token: ethereum|base|0xA9A434f0aBCE2f3e7073752046545530e32DE6cF
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: ethereum|katana|0xe064aee7327b19ba636c8d8b594f73572b95ea29
      - token: sealevel|solanamainnet|5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/ctUSD/logo.svg
    name: Citrea USD
    standard: EvmHypCrossCollateralRouter
    symbol: ctUSD
  - addressOrDenom: "0xd4463cB3c90b3F49c673310BEC9bC18311134B47"
    chainName: ethereum
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|arbitrum|0x824353938ee1361265097acC9E329828e3455c15
      - token: ethereum|base|0xA9A434f0aBCE2f3e7073752046545530e32DE6cF
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|katana|0xe064aee7327b19ba636c8d8b594f73572b95ea29
      - token: sealevel|solanamainnet|5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCrossCollateralRouter
    symbol: USDC
  - addressOrDenom: HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    chainName: solanamainnet
    coinGeckoId: usd-coin
    collateralAddressOrDenom: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|arbitrum|0x824353938ee1361265097acC9E329828e3455c15
      - token: ethereum|base|0xA9A434f0aBCE2f3e7073752046545530e32DE6cF
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|katana|0xe064aee7327b19ba636c8d8b594f73572b95ea29
      - token: sealevel|solanamainnet|5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: SealevelHypCrossCollateral
    symbol: USDC
  - addressOrDenom: 5FDu9EkpgUom1MtVso5x1eA7bAuf3CdffKk7hx2JQA1y
    chainName: solanamainnet
    coinGeckoId: xo-cash
    collateralAddressOrDenom: xoUSDq85Rjsb6SbUwJyreFgeWQvxdkT7R3c3g7s6p5Y
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|arbitrum|0x824353938ee1361265097acC9E329828e3455c15
      - token: ethereum|base|0xA9A434f0aBCE2f3e7073752046545530e32DE6cF
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/ctUSD/xo-cash-logo.png
    name: XO Cash
    standard: SealevelHypCrossCollateral
    symbol: XO
  - addressOrDenom: "0xe064aee7327b19ba636c8d8b594f73572b95ea29"
    chainName: katana
    coinGeckoId: vaultbridge-bridged-usdc-katana
    collateralAddressOrDenom: "0x203A662b0BD271A6ed5a60EdFbd04bFce608FD36"
    connections:
      - token: ethereum|arbitrum|0x62fe676dff1e7ABBCcbedc8BABc993827b9fb189
      - token: ethereum|base|0xd54A15f8dF8C6dD9Ef3b5589BE0bF37EC6f61F91
      - token: ethereum|citrea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|ethereum|0xd4463cB3c90b3F49c673310BEC9bC18311134B47
      - token: sealevel|solanamainnet|HxwQM6D6FpqZJkemVKyhQpD2k8cHefg1PG4iWH5aXdrr
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: Vault Bridge USDC
    standard: EvmHypCrossCollateralRouter
    symbol: vbUSDC
