# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xbe103Cb39B205d8AcB9E71E29dF3A7FDB87716E2"
    chainName: arbitrum
    decimals: 6
    name: Tether USD
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB-STAGE
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0xFb2727dD89f39D5527d6ff4e05D61b02BF8cd492"
    chainName: base
    decimals: 6
    name: Tether USD
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB-STAGE
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0xb2638bD8B1D06255a9e8dBFdeec9af9Af718e8ac"
    chainName: bsc
    decimals: 18
    name: Tether USD
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB-STAGE
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0xbBa1938ff861c77eA1687225B9C33554379Ef327"
    chainName: ethereum
    decimals: 6
    name: Tether USD
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB-STAGE
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0x72ad40cAc1c1128B04Fea4fb07fd2449ba19Fe3e"
    chainName: polygon
    decimals: 6
    name: USDT0
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB-STAGE
    tokenType: atomicLocalRebalancing
