# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x06De5F702f35f1293DA341E047CF50AcC3D30bEb"
    chainName: base
    decimals: 6
    name: Moonpay Staging Local Rebalancing Bridge
    standard: EvmHypCollateral
    symbol: mpsALRB
