# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xD171C42548c185605BD157AbF427bBc965DE8d81"
    chainName: arbitrum
    decimals: 6
    name: USD₮0
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0xB3c707946DB9AC7048Fe88d402E6941a12E92020"
    chainName: base
    decimals: 6
    name: Tether USD
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0x17332Cd9198bC16bdfd164e0C6C60F22c2E53724"
    chainName: bsc
    decimals: 18
    name: Tether USD
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0xdbB90710A5Fe76C0ddDc6445FF8C815a0ac94e11"
    chainName: ethereum
    decimals: 6
    name: Tether USD
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB
    tokenType: atomicLocalRebalancing
  - addressOrDenom: "0x5ac869Ea4eb878001eCF882E471a447D57DE1968"
    chainName: polygon
    decimals: 6
    name: USDT0
    standard: EvmAtomicLocalRebalancingBridge
    symbol: mpALRB
    tokenType: atomicLocalRebalancing
