# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x7b1449c0e9A9123465C39e499Fc8d0a53867d163"
    chainName: base
    decimals: 6
    name: Moonpay Staging Local Rebalancing Bridge
    standard: EvmHypCollateral
    symbol: mpsALRB
