# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886"
    chainName: kiichain
    connections:
      - token: ethereum|bsc|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|polygon|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|base|0x3EBA6644819546C44Eb3e7c3A92f034f921dcA80
      - token: ethereum|ethereum|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
    decimals: 18
    logoURI: /deployments/warp_routes/KII/logo.png
    name: Kiichain
    standard: EvmHypNative
    symbol: KII
  - addressOrDenom: "0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886"
    chainName: bsc
    connections:
      - token: ethereum|kiichain|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|polygon|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|base|0x3EBA6644819546C44Eb3e7c3A92f034f921dcA80
      - token: ethereum|ethereum|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
    decimals: 18
    logoURI: /deployments/warp_routes/KII/logo.png
    name: Kiichain
    standard: EvmHypSynthetic
    symbol: KII
  - addressOrDenom: "0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886"
    chainName: polygon
    connections:
      - token: ethereum|kiichain|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|bsc|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|base|0x3EBA6644819546C44Eb3e7c3A92f034f921dcA80
      - token: ethereum|ethereum|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
    decimals: 18
    logoURI: /deployments/warp_routes/KII/logo.png
    name: Kiichain
    standard: EvmHypSynthetic
    symbol: KII
  - addressOrDenom: "0x3EBA6644819546C44Eb3e7c3A92f034f921dcA80"
    chainName: base
    connections:
      - token: ethereum|kiichain|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|bsc|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|polygon|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|ethereum|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
    decimals: 18
    logoURI: /deployments/warp_routes/KII/logo.png
    name: Kiichain
    standard: EvmHypSynthetic
    symbol: KII
  - addressOrDenom: "0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886"
    chainName: ethereum
    connections:
      - token: ethereum|kiichain|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|bsc|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|polygon|0xEEC6574eAbBa52bac3f0277F2cD5Ac7e67197886
      - token: ethereum|base|0x3EBA6644819546C44Eb3e7c3A92f034f921dcA80
    decimals: 18
    logoURI: /deployments/warp_routes/KII/logo.png
    name: Kiichain
    standard: EvmHypSynthetic
    symbol: KII
