# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: base
    standard: EvmHypSynthetic
    decimals: 18
    symbol: KII
    name: kiichain
    addressOrDenom: "0x3Eb6F7e90127792EbDe3C17019591C92f8B3255b"
    logoURI: /deployments/warp_routes/KII/logo.png
    connections:
      - token: ethereum|kiichain|0xee9CB26259E98A8F24fc8D265AEfa09B4f3AcAb7
      - token: ethereum|bsc|0x601D2D3Ba5e2F8a0D9da6653fda2a6F4A9DbbD0a
      - token: ethereum|polygon|0x8E281996FCF50b54D7772e4a2e24E0DF27B9D59f
      - token: ethereum|ethereum|0xE1206aF9d43966d440CEF6d78AbF4406602e90D2
  - chainName: bsc
    standard: EvmHypSynthetic
    decimals: 18
    symbol: KII
    name: kiichain
    addressOrDenom: "0x601D2D3Ba5e2F8a0D9da6653fda2a6F4A9DbbD0a"
    logoURI: /deployments/warp_routes/KII/logo.png
    connections:
      - token: ethereum|kiichain|0xee9CB26259E98A8F24fc8D265AEfa09B4f3AcAb7
      - token: ethereum|base|0x3Eb6F7e90127792EbDe3C17019591C92f8B3255b
      - token: ethereum|polygon|0x8E281996FCF50b54D7772e4a2e24E0DF27B9D59f
      - token: ethereum|ethereum|0xE1206aF9d43966d440CEF6d78AbF4406602e90D2
  - chainName: ethereum
    standard: EvmHypSynthetic
    decimals: 18
    symbol: KII
    name: kiichain
    addressOrDenom: "0xE1206aF9d43966d440CEF6d78AbF4406602e90D2"
    logoURI: /deployments/warp_routes/KII/logo.png
    connections:
      - token: ethereum|kiichain|0xee9CB26259E98A8F24fc8D265AEfa09B4f3AcAb7
      - token: ethereum|bsc|0x601D2D3Ba5e2F8a0D9da6653fda2a6F4A9DbbD0a
      - token: ethereum|base|0x3Eb6F7e90127792EbDe3C17019591C92f8B3255b
      - token: ethereum|polygon|0x8E281996FCF50b54D7772e4a2e24E0DF27B9D59f
  - chainName: kiichain
    standard: EvmHypNative
    decimals: 18
    symbol: KII
    name: KII
    addressOrDenom: "0xee9CB26259E98A8F24fc8D265AEfa09B4f3AcAb7"
    logoURI: /deployments/warp_routes/KII/logo.png
    connections:
      - token: ethereum|bsc|0x601D2D3Ba5e2F8a0D9da6653fda2a6F4A9DbbD0a
      - token: ethereum|base|0x3Eb6F7e90127792EbDe3C17019591C92f8B3255b
      - token: ethereum|polygon|0x8E281996FCF50b54D7772e4a2e24E0DF27B9D59f
      - token: ethereum|ethereum|0xE1206aF9d43966d440CEF6d78AbF4406602e90D2
  - chainName: polygon
    standard: EvmHypSynthetic
    decimals: 18
    symbol: KII
    name: kiichain
    addressOrDenom: "0x8E281996FCF50b54D7772e4a2e24E0DF27B9D59f"
    logoURI: /deployments/warp_routes/KII/logo.png
    connections:
      - token: ethereum|kiichain|0xee9CB26259E98A8F24fc8D265AEfa09B4f3AcAb7
      - token: ethereum|bsc|0x601D2D3Ba5e2F8a0D9da6653fda2a6F4A9DbbD0a
      - token: ethereum|base|0x3Eb6F7e90127792EbDe3C17019591C92f8B3255b
      - token: ethereum|ethereum|0xE1206aF9d43966d440CEF6d78AbF4406602e90D2
