# yaml-language-server: $schema=../schema.json
options:
  sealevel:
    altAddresses:
      solanamainnet:
        core: 3u4mzXkt38nyZvS1hBT1ZQF8C8f9Lho38WFeVz7hVykD
        warpSpecific:
          - GK5SRhjfbfeegaRTn2mF2TsakG6fQ53rW6mpbAVNnNsF
tokens:
  - addressOrDenom: hyp_warp_token_bat_v2.aleo/aleo1n6kjmle3t0prrwjgpwc87zytasmjdeud5rrwuuawk57ex85qr5fqcv8xzg
    chainName: aleo
    connections:
      - token: ethereum|ethereum|0x516e156e987175d74614cc2bC960f148A610f0b3
      - token: sealevel|solanamainnet|7CJFBsNC49upnVfMga2gj53deAjuuVchdceJQrJg5oA5
    decimals: 18
    logoURI: /deployments/warp_routes/BAT/logo.svg
    name: Basic Attention
    scale:
      denominator: 1
      numerator: 1
    standard: AleoHypSynthetic
    symbol: BAT
    tokenType: synthetic
  - addressOrDenom: "0x516e156e987175d74614cc2bC960f148A610f0b3"
    chainName: ethereum
    coinGeckoId: basic-attention-token
    collateralAddressOrDenom: "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
    connections:
      - token: aleo|aleo|hyp_warp_token_bat_v2.aleo/aleo1n6kjmle3t0prrwjgpwc87zytasmjdeud5rrwuuawk57ex85qr5fqcv8xzg
      - token: sealevel|solanamainnet|7CJFBsNC49upnVfMga2gj53deAjuuVchdceJQrJg5oA5
    decimals: 18
    logoURI: /deployments/warp_routes/BAT/logo.svg
    name: Basic Attention Token
    scale:
      denominator: 1
      numerator: 1
    standard: EvmHypCollateral
    symbol: BAT
    tokenType: collateral
  - addressOrDenom: 7CJFBsNC49upnVfMga2gj53deAjuuVchdceJQrJg5oA5
    chainName: solanamainnet
    coinGeckoId: basic-attention-token
    collateralAddressOrDenom: EPeUFDgHRxs9xxEPVaL6kfGQvCon7jmAWKVUHuux1Tpz
    connections:
      - token: aleo|aleo|hyp_warp_token_bat_v2.aleo/aleo1n6kjmle3t0prrwjgpwc87zytasmjdeud5rrwuuawk57ex85qr5fqcv8xzg
      - token: ethereum|ethereum|0x516e156e987175d74614cc2bC960f148A610f0b3
    decimals: 8
    logoURI: /deployments/warp_routes/BAT/logo.svg
    name: Basic Attention
    scale:
      denominator: 1
      numerator: 10000000000
    standard: SealevelHypCollateral
    symbol: BAT
    tokenType: collateral
