# yaml-language-server: $schema=../schema.json
options:
  sealevel:
    altAddresses:
      solanamainnet:
        core: 3u4mzXkt38nyZvS1hBT1ZQF8C8f9Lho38WFeVz7hVykD
        warpSpecific:
          - QgEtGAN65Atzeqr9b48V9jhsT4JVj136wFe2UNAjT8B
tokens:
  - addressOrDenom: hyp_warp_token_usdg_v2.aleo/aleo1s4r80dv7pcggdnzsavjv45r54zjydl2jn64dejerpk6pgnfj5cysj7zzuu
    chainName: aleo
    connections:
      - token: ethereum|ethereum|0xe5A2cCf532919f93855F324c1F8a7996065f53Da
      - token: sealevel|solanamainnet|AhNVa6VpZwDwgD3U66CGUwCMRcFSFiTfBse2D495SPxW
    decimals: 6
    logoURI: /deployments/warp_routes/USDG/logo.svg
    name: Global Dollar
    standard: AleoHypSynthetic
    symbol: USDG
    tokenType: synthetic
  - addressOrDenom: "0xe5A2cCf532919f93855F324c1F8a7996065f53Da"
    chainName: ethereum
    coinGeckoId: global-dollar
    collateralAddressOrDenom: "0xe343167631d89B6Ffc58B88d6b7fB0228795491D"
    connections:
      - token: aleo|aleo|hyp_warp_token_usdg_v2.aleo/aleo1s4r80dv7pcggdnzsavjv45r54zjydl2jn64dejerpk6pgnfj5cysj7zzuu
      - token: sealevel|solanamainnet|AhNVa6VpZwDwgD3U66CGUwCMRcFSFiTfBse2D495SPxW
    decimals: 6
    logoURI: /deployments/warp_routes/USDG/logo.svg
    name: Global Dollar
    standard: EvmHypCollateral
    symbol: USDG
    tokenType: collateral
  - addressOrDenom: AhNVa6VpZwDwgD3U66CGUwCMRcFSFiTfBse2D495SPxW
    chainName: solanamainnet
    coinGeckoId: global-dollar
    collateralAddressOrDenom: 2u1tszSeqZ3qBWF3uNGPFc8TzMk2tdiwknnRMWGWjGWH
    connections:
      - token: aleo|aleo|hyp_warp_token_usdg_v2.aleo/aleo1s4r80dv7pcggdnzsavjv45r54zjydl2jn64dejerpk6pgnfj5cysj7zzuu
      - token: ethereum|ethereum|0xe5A2cCf532919f93855F324c1F8a7996065f53Da
    decimals: 6
    logoURI: /deployments/warp_routes/USDG/logo.svg
    name: Global Dollar
    standard: SealevelHypCollateral
    symbol: USDG
    tokenType: collateral
