# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: hyp_warp_token_wbtc_v2.aleo/aleo1240fsvz2dhmj0cdtt8mc0yc8um9fmu236rqcl2qnlj9703hd2vpsdwyrtf
    chainName: aleo
    connections:
      - token: ethereum|ethereum|0x20CDC85778b732073F7EecEF3DF25c0d310f8772
      - token: ethereum|hyperevm|0xefafEE2F52c083c5aaB09c4AF65Adc966bbf1479
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: AleoHypSynthetic
    symbol: WBTC
    tokenType: synthetic
  - addressOrDenom: "0x20CDC85778b732073F7EecEF3DF25c0d310f8772"
    chainName: ethereum
    coinGeckoId: wrapped-bitcoin
    collateralAddressOrDenom: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
    connections:
      - token: aleo|aleo|hyp_warp_token_wbtc_v2.aleo/aleo1240fsvz2dhmj0cdtt8mc0yc8um9fmu236rqcl2qnlj9703hd2vpsdwyrtf
      - token: ethereum|hyperevm|0xefafEE2F52c083c5aaB09c4AF65Adc966bbf1479
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
    tokenType: collateral
  - addressOrDenom: "0xefafEE2F52c083c5aaB09c4AF65Adc966bbf1479"
    chainName: hyperevm
    coinGeckoId: wrapped-bitcoin
    collateralAddressOrDenom: "0x9FDBdA0A5e284c32744D2f17Ee5c74B284993463"
    connections:
      - token: aleo|aleo|hyp_warp_token_wbtc_v2.aleo/aleo1240fsvz2dhmj0cdtt8mc0yc8um9fmu236rqcl2qnlj9703hd2vpsdwyrtf
      - token: ethereum|ethereum|0x20CDC85778b732073F7EecEF3DF25c0d310f8772
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
    tokenType: collateral
