tokens:
  - addressOrDenom: test_hyp_warp_token_wbtc.aleo/aleo1x29rhydhtnjaekxma5hnhmgy2q36vx244rqrmpqmecc4wg3uyu9q0sll0m
    chainName: aleotestnet
    connections:
      - token: ethereum|sepolia|0x2A872Ae01375A5ca7e044cb0e75cb97621Ca954A
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: AleoHypSynthetic
    symbol: WBTC
  - addressOrDenom: "0x2A872Ae01375A5ca7e044cb0e75cb97621Ca954A"
    chainName: sepolia
    collateralAddressOrDenom: "0x52eea312378ef46140ebe67de8a143ba2304fd7c"
    connections:
      - token: aleo|aleotestnet|test_hyp_warp_token_wbtc.aleo/aleo1x29rhydhtnjaekxma5hnhmgy2q36vx244rqrmpqmecc4wg3uyu9q0sll0m
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
