bsc:
  decimals: 8
  name: Wrapped BTC
  owner: "0x269Af9E53192AF49a22ff47e30b89dE1375AE1fd"
  symbol: WBTC
  token: "0x39665e85a68a4d7328b8799135E2ff301a0Ca86f"
  tokenFee:
    feeContracts:
      ethereum:
        bps: 10
        owner: "0xA0e41Ab972294A8f7CD1599BB76AdDB6bAE24556"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      solanamainnet:
        bps: 10
        owner: "0xA0e41Ab972294A8f7CD1599BB76AdDB6bAE24556"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      tron:
        bps: 10
        owner: "0xA0e41Ab972294A8f7CD1599BB76AdDB6bAE24556"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
    owner: "0xA0e41Ab972294A8f7CD1599BB76AdDB6bAE24556"
    type: RoutingFee
  type: collateral
ethereum:
  decimals: 8
  name: Wrapped BTC
  owner: "0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6"
  symbol: WBTC
  token: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
  tokenFee:
    feeContracts:
      bsc:
        bps: 10
        owner: "0x8Ff4c563f26db00e65bD93d9f662A51c304C09b0"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      solanamainnet:
        bps: 10
        owner: "0x8Ff4c563f26db00e65bD93d9f662A51c304C09b0"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      tron:
        bps: 10
        owner: "0x8Ff4c563f26db00e65bD93d9f662A51c304C09b0"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
    owner: "0x8Ff4c563f26db00e65bD93d9f662A51c304C09b0"
    type: RoutingFee
  type: collateral
solanamainnet:
  decimals: 8
  gas: 300000
  hook: BhNcatUDC2D5JTyeaqrdSukiVFsEHK7e3hVmKMztwefv
  name: Wrapped BTC
  owner: BNGDJ1h9brgt6FFVd8No1TVAH48Fp44d7jkuydr1URwJ
  symbol: WBTC
  token: 5XZw2LKTyrfvfiskJ78AMpackRjPcyCif1WhUsPDuVqQ
  tokenFee:
    feeContracts:
      bsc:
        bps: 10
        owner: BNGDJ1h9brgt6FFVd8No1TVAH48Fp44d7jkuydr1URwJ
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      ethereum:
        bps: 10
        owner: BNGDJ1h9brgt6FFVd8No1TVAH48Fp44d7jkuydr1URwJ
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      tron:
        bps: 10
        owner: BNGDJ1h9brgt6FFVd8No1TVAH48Fp44d7jkuydr1URwJ
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
    owner: BNGDJ1h9brgt6FFVd8No1TVAH48Fp44d7jkuydr1URwJ
    type: RoutingFee
  type: collateral
tron:
  decimals: 8
  name: Wrapped BTC
  owner: "0xB960616C7E2ee0F2a296A4b2B9D0b3308E23A69D"
  symbol: WBTC
  token: "0xf95335a4d42db4b70a9688a393279f2c90fa1025"
  tokenFee:
    feeContracts:
      bsc:
        bps: 10
        owner: "0xa5A136994e739E9042820C88F24041165767cBF9"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      ethereum:
        bps: 10
        owner: "0xa5A136994e739E9042820C88F24041165767cBF9"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
      solanamainnet:
        bps: 10
        owner: "0xa5A136994e739E9042820C88F24041165767cBF9"
        quoteSigners:
          - "0xEd1829805De615eEFC7303766D395Ea0a1B2b04d"
        type: OffchainQuotedLinearFee
    owner: "0xa5A136994e739E9042820C88F24041165767cBF9"
    type: RoutingFee
  type: collateral
