# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xb7d28Dc6C6EbA10AB67255841FA521F83f35C6b2"
    chainName: bsc
    collateralAddressOrDenom: "0xf263cc32caed261a819713f3dcc494a96c3e5111"
    connections:
      - token: ethereum|eni|0x0587E4E093Cd820eda59EcF0FD73544cE65B4775
    decimals: 18
    logoURI: /deployments/warp_routes/1Piece/logo.png
    name: OnePiece
    standard: EvmHypCollateral
    symbol: 1Piece
  - addressOrDenom: "0x0587E4E093Cd820eda59EcF0FD73544cE65B4775"
    chainName: eni
    connections:
      - token: ethereum|bsc|0xb7d28Dc6C6EbA10AB67255841FA521F83f35C6b2
    decimals: 18
    logoURI: /deployments/warp_routes/1Piece/logo.png
    name: OnePiece
    standard: EvmHypSynthetic
    symbol: 1Piece
