# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x8cAd676141FeadB6aCA5eF661E835d5957644033"
    chainName: arbitrum
    connections:
      - token: ethereum|base|0x2E968fB88998a6303535Ac637C809119ECAd4a4b
      - token: ethereum|bsc|0x097acf27503753e77bCA940277806156C5925B81
      - token: ethereum|ethereum|0x863F08A3d3B14fbD3D42fFD061D0e290F7dBC538
      - token: ethereum|hyperevm|0xdFC12a5cF04Bc91BE4aF0E3Bc46A3CDADB1f86Af
      - token: sealevel|solanamainnet|EFuxu8VZJJvWZohJgjsbgXvRifySusuMv7FmSEvzDRoz
      - token: ethereum|nesachain|0xbb0AE51BCa526cF313b6a95BfaB020794af6C394
    decimals: 18
    logoURI: /deployments/warp_routes/NES/logo.svg
    name: Nesa
    standard: EvmHypSynthetic
    symbol: NES
    tokenType: synthetic
  - addressOrDenom: "0x2E968fB88998a6303535Ac637C809119ECAd4a4b"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0x8cAd676141FeadB6aCA5eF661E835d5957644033
      - token: ethereum|bsc|0x097acf27503753e77bCA940277806156C5925B81
      - token: ethereum|ethereum|0x863F08A3d3B14fbD3D42fFD061D0e290F7dBC538
      - token: ethereum|hyperevm|0xdFC12a5cF04Bc91BE4aF0E3Bc46A3CDADB1f86Af
      - token: sealevel|solanamainnet|EFuxu8VZJJvWZohJgjsbgXvRifySusuMv7FmSEvzDRoz
      - token: ethereum|nesachain|0xbb0AE51BCa526cF313b6a95BfaB020794af6C394
    decimals: 18
    logoURI: /deployments/warp_routes/NES/logo.svg
    name: Nesa
    standard: EvmHypSynthetic
    symbol: NES
    tokenType: synthetic
  - addressOrDenom: "0x097acf27503753e77bCA940277806156C5925B81"
    chainName: bsc
    connections:
      - token: ethereum|arbitrum|0x8cAd676141FeadB6aCA5eF661E835d5957644033
      - token: ethereum|base|0x2E968fB88998a6303535Ac637C809119ECAd4a4b
      - token: ethereum|ethereum|0x863F08A3d3B14fbD3D42fFD061D0e290F7dBC538
      - token: ethereum|hyperevm|0xdFC12a5cF04Bc91BE4aF0E3Bc46A3CDADB1f86Af
      - token: sealevel|solanamainnet|EFuxu8VZJJvWZohJgjsbgXvRifySusuMv7FmSEvzDRoz
      - token: ethereum|nesachain|0xbb0AE51BCa526cF313b6a95BfaB020794af6C394
    decimals: 18
    logoURI: /deployments/warp_routes/NES/logo.svg
    name: Nesa
    standard: EvmHypSynthetic
    symbol: NES
    tokenType: synthetic
  - addressOrDenom: "0x863F08A3d3B14fbD3D42fFD061D0e290F7dBC538"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0x8cAd676141FeadB6aCA5eF661E835d5957644033
      - token: ethereum|base|0x2E968fB88998a6303535Ac637C809119ECAd4a4b
      - token: ethereum|bsc|0x097acf27503753e77bCA940277806156C5925B81
      - token: ethereum|hyperevm|0xdFC12a5cF04Bc91BE4aF0E3Bc46A3CDADB1f86Af
      - token: sealevel|solanamainnet|EFuxu8VZJJvWZohJgjsbgXvRifySusuMv7FmSEvzDRoz
      - token: ethereum|nesachain|0xbb0AE51BCa526cF313b6a95BfaB020794af6C394
    decimals: 18
    logoURI: /deployments/warp_routes/NES/logo.svg
    name: Nesa
    standard: EvmHypSynthetic
    symbol: NES
    tokenType: synthetic
  - addressOrDenom: "0xdFC12a5cF04Bc91BE4aF0E3Bc46A3CDADB1f86Af"
    chainName: hyperevm
    connections:
      - token: ethereum|arbitrum|0x8cAd676141FeadB6aCA5eF661E835d5957644033
      - token: ethereum|base|0x2E968fB88998a6303535Ac637C809119ECAd4a4b
      - token: ethereum|bsc|0x097acf27503753e77bCA940277806156C5925B81
      - token: ethereum|ethereum|0x863F08A3d3B14fbD3D42fFD061D0e290F7dBC538
      - token: sealevel|solanamainnet|EFuxu8VZJJvWZohJgjsbgXvRifySusuMv7FmSEvzDRoz
      - token: ethereum|nesachain|0xbb0AE51BCa526cF313b6a95BfaB020794af6C394
    decimals: 18
    logoURI: /deployments/warp_routes/NES/logo.svg
    name: Nesa
    standard: EvmHypSynthetic
    symbol: NES
    tokenType: synthetic
  - addressOrDenom: EFuxu8VZJJvWZohJgjsbgXvRifySusuMv7FmSEvzDRoz
    chainName: solanamainnet
    connections:
      - token: ethereum|arbitrum|0x8cAd676141FeadB6aCA5eF661E835d5957644033
      - token: ethereum|base|0x2E968fB88998a6303535Ac637C809119ECAd4a4b
      - token: ethereum|bsc|0x097acf27503753e77bCA940277806156C5925B81
      - token: ethereum|ethereum|0x863F08A3d3B14fbD3D42fFD061D0e290F7dBC538
      - token: ethereum|hyperevm|0xdFC12a5cF04Bc91BE4aF0E3Bc46A3CDADB1f86Af
      - token: ethereum|nesachain|0xbb0AE51BCa526cF313b6a95BfaB020794af6C394
    decimals: 9
    logoURI: /deployments/warp_routes/NES/logo.svg
    name: Nesa
    scale:
      denominator: 1
      numerator: 1000000000
    standard: SealevelHypSynthetic
    symbol: NES
    tokenType: synthetic
  - addressOrDenom: "0xbb0AE51BCa526cF313b6a95BfaB020794af6C394"
    chainName: nesachain
    coinGeckoId: nesa
    connections:
      - token: ethereum|arbitrum|0x8cAd676141FeadB6aCA5eF661E835d5957644033
      - token: ethereum|base|0x2E968fB88998a6303535Ac637C809119ECAd4a4b
      - token: ethereum|bsc|0x097acf27503753e77bCA940277806156C5925B81
      - token: ethereum|ethereum|0x863F08A3d3B14fbD3D42fFD061D0e290F7dBC538
      - token: ethereum|hyperevm|0xdFC12a5cF04Bc91BE4aF0E3Bc46A3CDADB1f86Af
      - token: sealevel|solanamainnet|EFuxu8VZJJvWZohJgjsbgXvRifySusuMv7FmSEvzDRoz
    decimals: 18
    logoURI: /deployments/warp_routes/NES/logo.svg
    name: NES
    standard: EvmHypNative
    symbol: NES
    tokenType: native
