/**
 * A list of chains managed by the Hyperlane core team.
 * Hyperlane can be deployed permissionlessly to any chain but for
 * convenience the core team maintains some deployments.
 */
export enum CoreChain {
  alfajores = 'alfajores',
  ancient8 = 'ancient8',
  arbitrum = 'arbitrum',
  avalanche = 'avalanche',
  base = 'base',
  blast = 'blast',
  bob = 'bob',
  bsc = 'bsc',
  bsctestnet = 'bsctestnet',
  celo = 'celo',
  cheesechain = 'cheesechain',
  chiado = 'chiado',
  connextsepolia = 'connextsepolia',
  cyber = 'cyber',
  degen = 'degen',
  eclipsetestnet = 'eclipsetestnet',
  endurance = 'endurance',
  ethereum = 'ethereum',
  fraxtal = 'fraxtal',
  fuji = 'fuji',
  fusemainnet = 'fusemainnet',
  gnosis = 'gnosis',
  inevm = 'inevm',
  injective = 'injective',
  kroma = 'kroma',
  linea = 'linea',
  lisk = 'lisk',
  lukso = 'lukso',
  mantapacific = 'mantapacific',
  mantle = 'mantle',
  merlin = 'merlin',
  metis = 'metis',
  mint = 'mint',
  moonbeam = 'moonbeam',
  nautilus = 'nautilus',
  neutron = 'neutron',
  optimism = 'optimism',
  plumetestnet = 'plumetestnet',
  polygon = 'polygon',
  polygonzkevm = 'polygonzkevm',
  proofofplay = 'proofofplay',
  proteustestnet = 'proteustestnet',
  real = 'real',
  redstone = 'redstone',
  sanko = 'sanko',
  scroll = 'scroll',
  scrollsepolia = 'scrollsepolia',
  sei = 'sei',
  sepolia = 'sepolia',
  solana = 'solana',
  solanadevnet = 'solanadevnet',
  solanatestnet = 'solanatestnet',
  superpositiontestnet = 'superpositiontestnet',
  taiko = 'taiko',
  tangle = 'tangle',
  viction = 'viction',
  worldchain = 'worldchain',
  xai = 'xai',
  xlayer = 'xlayer',
  zetachain = 'zetachain',
  zircuit = 'zircuit',
  zoramainnet = 'zoramainnet',
}

export type CoreChainName = keyof typeof CoreChain;

export const CoreMainnets: Array<CoreChainName> = [
  CoreChain.ancient8,
  CoreChain.arbitrum,
  CoreChain.avalanche,
  CoreChain.base,
  CoreChain.blast,
  CoreChain.bob,
  CoreChain.bsc,
  CoreChain.celo,
  CoreChain.cheesechain,
  CoreChain.cyber,
  CoreChain.degen,
  CoreChain.endurance,
  CoreChain.ethereum,
  CoreChain.fraxtal,
  CoreChain.fusemainnet,
  CoreChain.gnosis,
  CoreChain.inevm,
  CoreChain.injective,
  CoreChain.kroma,
  CoreChain.linea,
  CoreChain.lisk,
  CoreChain.lukso,
  CoreChain.mantapacific,
  CoreChain.mantle,
  CoreChain.merlin,
  CoreChain.metis,
  CoreChain.mint,
  CoreChain.moonbeam,
  CoreChain.neutron,
  CoreChain.optimism,
  CoreChain.polygon,
  CoreChain.polygonzkevm,
  CoreChain.proofofplay,
  CoreChain.real,
  CoreChain.redstone,
  CoreChain.sanko,
  CoreChain.scroll,
  CoreChain.sei,
  CoreChain.taiko,
  CoreChain.tangle,
  CoreChain.viction,
  CoreChain.worldchain,
  CoreChain.xai,
  CoreChain.xlayer,
  CoreChain.zetachain,
  CoreChain.zircuit,
  CoreChain.zoramainnet,
  // CoreChains.solana,
];

export const CoreTestnets: Array<CoreChainName> = [
  CoreChain.alfajores,
  CoreChain.bsctestnet,
  CoreChain.chiado,
  CoreChain.connextsepolia,
  CoreChain.eclipsetestnet,
  CoreChain.fuji,
  CoreChain.plumetestnet,
  CoreChain.proteustestnet,
  CoreChain.scrollsepolia,
  CoreChain.sepolia,
  CoreChain.solanadevnet,
  CoreChain.solanatestnet,
  CoreChain.superpositiontestnet,
];

export const CoreChains: Array<CoreChainName> = [...CoreMainnets, ...CoreTestnets];
