/**
 * A list of chains managed by the Hyperlane core team.
 * Hyperlane can be deployed permissionlessly to any chain but for
 * convenience the core team maintains some deployments.
 */
export enum CoreChain {
  alfajores = 'alfajores',
  ancient8 = 'ancient8',
  arbitrum = 'arbitrum',
  arbitrumsepolia = 'arbitrumsepolia',
  astar = 'astar',
  astarzkevm = 'astarzkevm',
  avalanche = 'avalanche',
  base = 'base',
  basesepolia = 'basesepolia',
  bitlayer = 'bitlayer',
  blast = 'blast',
  bob = 'bob',
  bsc = 'bsc',
  bsctestnet = 'bsctestnet',
  celo = 'celo',
  cheesechain = 'cheesechain',
  connextsepolia = 'connextsepolia',
  coredao = 'coredao',
  cyber = 'cyber',
  degen = 'degen',
  dogechain = 'dogechain',
  ecotestnet = 'ecotestnet',
  eclipsetestnet = 'eclipsetestnet',
  endurance = 'endurance',
  ethereum = 'ethereum',
  flare = 'flare',
  fraxtal = 'fraxtal',
  fuji = 'fuji',
  fusemainnet = 'fusemainnet',
  gnosis = 'gnosis',
  holesky = 'holesky',
  inevm = 'inevm',
  injective = 'injective',
  kroma = 'kroma',
  linea = 'linea',
  lisk = 'lisk',
  lukso = 'lukso',
  mantapacific = 'mantapacific',
  mantle = 'mantle',
  merlin = 'merlin',
  metis = 'metis',
  mint = 'mint',
  molten = 'molten',
  moonbeam = 'moonbeam',
  nautilus = 'nautilus',
  neutron = 'neutron',
  optimism = 'optimism',
  optimismsepolia = 'optimismsepolia',
  plumetestnet = 'plumetestnet',
  polygon = 'polygon',
  polygonamoy = 'polygonamoy',
  polygonzkevm = 'polygonzkevm',
  proofofplay = 'proofofplay',
  real = 'real',
  redstone = 'redstone',
  sanko = 'sanko',
  scroll = 'scroll',
  scrollsepolia = 'scrollsepolia',
  sei = 'sei',
  sepolia = 'sepolia',
  shibarium = 'shibarium',
  solana = 'solana',
  solanatestnet = 'solanatestnet',
  superpositiontestnet = 'superpositiontestnet',
  taiko = 'taiko',
  tangle = 'tangle',
  viction = 'viction',
  worldchain = 'worldchain',
  xai = 'xai',
  xlayer = 'xlayer',
  zetachain = 'zetachain',
  zircuit = 'zircuit',
  zoramainnet = 'zoramainnet',
}

export type CoreChainName = keyof typeof CoreChain;

export const CoreMainnets: Array<CoreChainName> = [
  CoreChain.ancient8,
  CoreChain.arbitrum,
  CoreChain.astar,
  CoreChain.astarzkevm,
  CoreChain.avalanche,
  CoreChain.base,
  CoreChain.bitlayer,
  CoreChain.blast,
  CoreChain.bob,
  CoreChain.bsc,
  CoreChain.celo,
  CoreChain.cheesechain,
  CoreChain.coredao,
  CoreChain.cyber,
  CoreChain.degen,
  CoreChain.dogechain,
  CoreChain.endurance,
  CoreChain.ethereum,
  CoreChain.flare,
  CoreChain.fraxtal,
  CoreChain.fusemainnet,
  CoreChain.gnosis,
  CoreChain.inevm,
  CoreChain.injective,
  CoreChain.kroma,
  CoreChain.linea,
  CoreChain.lisk,
  CoreChain.lukso,
  CoreChain.mantapacific,
  CoreChain.mantle,
  CoreChain.merlin,
  CoreChain.metis,
  CoreChain.mint,
  CoreChain.molten,
  CoreChain.moonbeam,
  CoreChain.neutron,
  CoreChain.optimism,
  CoreChain.polygon,
  CoreChain.polygonzkevm,
  CoreChain.proofofplay,
  CoreChain.real,
  CoreChain.redstone,
  CoreChain.sanko,
  CoreChain.scroll,
  CoreChain.sei,
  CoreChain.shibarium,
  CoreChain.taiko,
  CoreChain.tangle,
  CoreChain.viction,
  CoreChain.worldchain,
  CoreChain.xai,
  CoreChain.xlayer,
  CoreChain.zetachain,
  CoreChain.zircuit,
  CoreChain.zoramainnet,
  // CoreChains.solana,
];

export const CoreTestnets: Array<CoreChainName> = [
  CoreChain.alfajores,
  CoreChain.arbitrumsepolia,
  CoreChain.basesepolia,
  CoreChain.bsctestnet,
  CoreChain.connextsepolia,
  CoreChain.ecotestnet,
  CoreChain.eclipsetestnet,
  CoreChain.fuji,
  CoreChain.holesky,
  CoreChain.optimismsepolia,
  CoreChain.plumetestnet,
  CoreChain.polygonamoy,
  CoreChain.scrollsepolia,
  CoreChain.sepolia,
  CoreChain.solanatestnet,
  CoreChain.superpositiontestnet,
];

export const CoreChains: Array<CoreChainName> = [...CoreMainnets, ...CoreTestnets];
