# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml
    chainName: terraclassictestnet
    collateralAddressOrDenom: uluna
    connections:
      - token: ethereum|bsctestnet|0x2144be4477202ba2d50c9a8be3181241878cf7d8
      - token: ethereum|sepolia|0x224a4419D7FA69D3bEbAbce574c7c84B48D829b4
      - token: sealevel|solanatestnet|62FHbCoeg3sRy4yurm6MUisLtAD7HM7vkJVyjM1BdhcK
    decimals: 6
    logoURI: /deployments/warp_routes/LUNC/logo.svg
    name: Luna Classic
    standard: CwHypCollateral
    symbol: LUNC
  - addressOrDenom: "0x2144be4477202ba2d50c9a8be3181241878cf7d8"
    chainName: bsctestnet
    connections:
      - token: cosmos|terraclassictestnet|terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml
    decimals: 6
    logoURI: /deployments/warp_routes/LUNC/logo.svg
    name: Luna Classic
    standard: EvmHypSynthetic
    symbol: LUNC
  - addressOrDenom: "0x224a4419D7FA69D3bEbAbce574c7c84B48D829b4"
    chainName: sepolia
    connections:
      - token: cosmos|terraclassictestnet|terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml
    decimals: 6
    logoURI: /deployments/warp_routes/LUNC/logo.svg
    name: Luna Classic
    standard: EvmHypSynthetic
    symbol: LUNC
  - addressOrDenom: 62FHbCoeg3sRy4yurm6MUisLtAD7HM7vkJVyjM1BdhcK
    chainName: solanatestnet
    collateralAddressOrDenom: CjJkBpL2QKyXmFUzb3uzNQZLQcAr5hLtThvpgM2NERnL
    connections:
      - token: cosmos|terraclassictestnet|terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml
    decimals: 6
    logoURI: /deployments/warp_routes/LUNC/logo.svg
    name: Luna Classic
    standard: SealevelHypSynthetic
    symbol: LUNC
